config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show  #アクション
    # Itemモデルのfindメソッドを使用して、パラメータの値に一致するidのデータを検索している
    # 取得したデータを@itemというインスタンス変数にセットする
    @item = Item.find(params[:id])  
  end
  def index
    @items = Item.all 
  end
  def new
    @item = Item.new
  end
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to @item
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    #@item = Item.find(params[:id])
    @item = Item.find(params[:id])
    #@item.update(item_params)
    @item.update(item_params)
    redirect_to @item
  end
  def destroy
    #destroy=削除
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end


  private

  # params.require(key).permit(filter)
  # key
  #   Strong Parameters を適用したい params の key を指定する。
  # filter
  #   Strong Parameters で許可するカラムを指定する。

  def item_params
    params.require(:item).permit(:name, :price, :seller, :description, :email, :image_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<!-- app/views/items/new.html.erb -->

<h1>商品更新フォーム</h1>
<%= form_with model: @item, local: true do |form| %>
  <p>
    商品名：<br>
    <%= form.text_field :name %>
  </p>
  <p>
    商品詳細：<br>
    <%= form.text_area :description %>
  </p>
  <p>
    価格：<br>
    <%= form.number_field :price %>
  </p>
  <p>
    出品者：<br>
    <%= form.text_field :seller %>
  </p>
  <p>
    電子メール：<br>
    <%= form.text_field :email %>
  </p>
  <p>
    商品画像URL：<br>
    <%= form.text_area :image_url %>
  </p>

  <%= form.submit :"更新" %>

<% end %>

app/views/items/index.html.erb
<h1>出品商品一覧</h1>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.name, item %></li>
  <% end %>
</ul>
<%= link_to "出品する", new_item_path %>

app/views/items/new.html.erb
<!-- app/views/items/new.html.erb -->

<h1>商品登録フォーム</h1>
<%= form_with model: @item, local: true do |form| %>
  <p>
    商品名：<br>
    <%= form.text_field :name %>
  </p>
  <p>
    商品詳細：<br>
    <%= form.text_area :description %>
  </p>
  <p>
    価格：<br>
    <%= form.number_field :price %>
  </p>
  <p>
    出品者：<br>
    <%= form.text_field :seller %>
  </p>
  <p>
    電子メール：<br>
    <%= form.text_field :email %>
  </p>
  <p>
    商品画像URL：<br>
    <%= form.text_area :image_url %>
  </p>

  <%= form.submit :"登録" %>

<% end %>

app/views/items/show.html.erb
<p>
  <b>商品名 : <%= @item.name %></b>
</p>
<p>
  <b>商品詳細 : <%= @item.description %></b>
</p>
<p>
  <b>価格 : <%= @item.price %></b>
</p>
<p>
  <b>出品者 : <%= @item.seller %></b>
</p>
<p>
  <b>電子メール : <%= @item.email %></b>
</p>
<p>
  <%= image_tag @item.image_url %>
</p>
<p>
  <%= link_to "編集", edit_item_path(@item) %>
  <%= link_to "削除", item_path(@item), method: :delete, data: {confirm: '削除してよろしいですか？'} %>

</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auction</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>